
tomcat.dev.lib = ${tomcat.dev}/lib
tomcat.dev.webapps = ${tomcat.dev}/webapps


tomcat.test.lib = ${tomcat.test}/lib
tomcat.test.webapps = ${tomcat.test}/webapps


tomcat.prod.lib = ${tomcat.prod}/lib
tomcat.prod.webapps = ${tomcat.prod}/webapps

#tomcat.test.webapps = ${tomcat.test}/webapps
#tomcat.prod.webapps = ${tomcat.prod}/webapps

#tomcat.prod.lib = ${tomcat.prod}/lib


# below is testing locally. Add your own server location here.
# NOTE: user must have a TOMCAT_HOME environment variable set
# for local testing and deployment now.
# local.server = D:/Tomcat/apache-tomcat-6.0.36